// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBHq05Z4gTvwWnzh7p05jFoEK7eXu9Gq4',
    appId: '1:460783170502:web:81b7c309f31ee62021f8c7',
    messagingSenderId: '460783170502',
    projectId: 'gso43a-nia',
    authDomain: 'gso43a-nia.firebaseapp.com',
    storageBucket: 'gso43a-nia.firebasestorage.app',
    measurementId: 'G-C0MGG9XKF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrY-C0-VPykLgy3fMn2sy9CoA1vxl33A',
    appId: '1:460783170502:android:b4a70b6b3118a41521f8c7',
    messagingSenderId: '460783170502',
    projectId: 'gso43a-nia',
    storageBucket: 'gso43a-nia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVlSz-1fLrQGGC1n4rXs3SGkSb8xSxqy0',
    appId: '1:460783170502:ios:c14d779203a943df21f8c7',
    messagingSenderId: '460783170502',
    projectId: 'gso43a-nia',
    storageBucket: 'gso43a-nia.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVlSz-1fLrQGGC1n4rXs3SGkSb8xSxqy0',
    appId: '1:460783170502:ios:c14d779203a943df21f8c7',
    messagingSenderId: '460783170502',
    projectId: 'gso43a-nia',
    storageBucket: 'gso43a-nia.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBHq05Z4gTvwWnzh7p05jFoEK7eXu9Gq4',
    appId: '1:460783170502:web:e31ce2af2eadf0ed21f8c7',
    messagingSenderId: '460783170502',
    projectId: 'gso43a-nia',
    authDomain: 'gso43a-nia.firebaseapp.com',
    storageBucket: 'gso43a-nia.firebasestorage.app',
    measurementId: 'G-HPXH23VSHH',
  );
}
